2013-12-12 23:56:19.026613
BarcodeKiller/na/Riven
47409152
cdzwvp8
ERROR:root:'47409152'
Traceback (most recent call last):
  File "bot.py", line 187, in <module>
    for entry in content[sid]['entries']:
KeyError: '47409152'



2013-12-12 23:57:11.273748
BarcodeKiller/na/Riven
47409152
cdzwvp8
ERROR:root:'47409152'
Traceback (most recent call last):
  File "bot.py", line 187, in <module>
    for entry in content[sid]['entries']:
KeyError: '47409152'



